### ISSUE TITLE
loading from app bundle (with ~ prefix) doesn't work

### ISSUE THREAD

**Issue by naderio** [NativeScript/nativescript-dev-typescript#16]
[loading from app bundle](https://docs.nativescript.org/runtimes/require.html#loading-files-from-the-app-bundle) is not functional.

is there any known workaround? (tsconfig mapping, path rewrite hook, ...)

**Comment by hdeshev** [comment]
Calling the plain JS `require` is possible in TypeScript as well. Use that instead.
