### ISSUE TITLE
tns-platform-declarations not included

### ISSUE THREAD

**Issue by adamvoss** [NativeScript/nativescript-dev-typescript#18]
All of the NativeScript declarations are not included when this package is included which can cause confusion and frustration for users when creating a NativeScript project with TypeScript then finding they do not have Intellisene support.

Eventually they may find [this answer by @NickIliev on how to install `tns-platform-declarations`](http://stackoverflow.com/a/37524018/1072626) and be able to continue with type information

It indicates there that the type information is not included due to space reasons.  If that is the case, is there something else that can be done to make it easier for users or more discoverable?

A more complete template for `tns create` is not an option because templates are mostly restricted to the app folder.  Maybe this package could prompt the user once if they want to include those references, or another package could be made available that gives a more complete references.d.ts?

**Comment by NickIliev** [comment]
The tns-platform-declarations are not included by default because of their enormous size (and also because not all developers will need access to native APIs)
