### ISSUE TITLE
Install 404

### ISSUE THREAD

**Issue by slaction** [NativeScript/nativescript-dev-typescript#27]
I recieved the following error when trying to install typescript into a fresh NativeScript project
------------

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/nativescript-dev-ts
npm ERR! 404 
npm ERR! 404  'nativescript-dev-ts' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404

**Comment by hdeshev** [comment]
The plugin name is `nativescript-dev-typescript`. Please use that one in your `npm install` command.

**Comment by slaction** [comment]
I was just using "tns install typescript".
