### ISSUE TITLE
Creating new projects still references ~0.7.0 ( and not 0.7.2)

### ISSUE THREAD

**Issue by mid787** [NativeScript/nativescript-dev-typescript#59]
Creating new projects via `tns create aaa --ng`  still references ~0.7.0 ( and not 0.7.2)

0.7.2 is stable and merged and fixed a problem of many "Recompiles"

https://github.com/NativeScript/nativescript-cli/issues/3687#issuecomment-398034476

Bump the version to the new version when creating new templates ?

![image](https://user-images.githubusercontent.com/2842123/43957339-2bc08f02-9cb0-11e8-96ab-8e5e14fbbec2.png)

**Comment by sis0k0** [comment]
Hi, @RoyiNamir! If `~0.7.0` is specified in the package.json, npm will install the latest 0.7 patch version which is `0.7.2`.

**Comment by mid787** [comment]
Yeah . thought it might be better to see 0.7.2 at first place. Thanks.
